hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [secured_area]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        google:
            type:                google
            client_id:           "votre_client_id"
            client_secret:       "votre_client_secret"
            redirect_route:      "hwi_oauth_connect_service_redirect"
